### ISSUE TITLE
Editing Appointments just just after midnight switches to PM

### ISSUE THREAD

**Issue by Nolan-Hamilton** [YCPRadioTelescope/Radio-Tele-Frontend#47]
**Editing Appointments just after midnight switches end time to PM**
When editing an appointment scheduled shortly after midnight, the appointment editor sets the appointment time to PM when it should be AM. This might have something to do with how the front-end converts from UTC to EST.
![image.png](https://images.zenhubusercontent.com/5e345d68b64bc27d98017230/e90c7bf2-b75c-47c7-b01b-3f91367c9df2)

![image.png](https://images.zenhubusercontent.com/5e345d68b64bc27d98017230/f0ec39e3-1c16-497e-8ac7-c9c01f27ab35)

Sometimes this happens to both the start and end time. If it happens to just the end time, then it tries to schedule an appointment 12 hours long which results in an allotted time cap error. 
This was discovered on  branch "#27-ImplementSpectraCyberConfig"

**Comment by lplaudsmith** [comment]
Last week I solved this bug. The problem stemmed from an over inclusive if statement that made it so the proper conversion was only done when the minute value was equal to 00. This was not intended and was removed. Additionally, comments were added so that future code editors would be able to better understand the chunk of code that handles AM/PM conversion.
